### ISSUE TITLE
如果是 require 图片资源，是否可以不包装 Module 返回？

### ISSUE THREAD

**Issue by shooterRao** [vite-plugin/vite-require#5]
您好！
现在有这么一段代码，在使用此插件后

转换前

```
const png = require('@/assets/logo.png');
console.log(png);
```

转换后

```
import * as png from '/src/assets/logo.png?import';
console.log(png);
```

这种有个问题，`import * as xxx` 导致返回的是个 `Module`，需要从 `default` 里面取值，在 js 里面直接使用会不太方便，如果是图片等一些静态资源的话，希望可以直接包装 `import xxx from 'xxx.png'` ，这样可以返回字符串，用起来顺畅很多~

期待您的答复，谢谢

**Comment by caoxiemeihao** [comment]
😂 言之有理

**Comment by shooterRao** [comment]
有些项目只用 require 加载静态资源(图片、音频...)，如果有参数支持配置自定义的 extname，不用 default 导出就更好了
希望可以支持这种情况😀

**Comment by caoxiemeihao** [comment]
The next version coming soon...

**Comment by shooterRao** [comment]
👍nice!

**Comment by caoxiemeihao** [comment]
Now, `vite-require` ![NPM version](https://img.shields.io/npm/v/vite-require.svg) is avaiable,
