### ISSUE TITLE
0.2.1 version require vite-plugin-dynamic-import utils emit error

### ISSUE THREAD

**Issue by shooterRao** [vite-plugin/vite-require#7]
0.2.1 emit error
`TypeError: Cannot destructure property 'normallyImporteeRE' of 'vite_plugin_dynamic_import_1.utils' as it is undefined.`

vite-plugin-dynamic-import@1.1.0 miss this export，emit error in vite-require
`export * as utils from './utils'`

1.1.0
https://github.com/vite-plugin/vite-plugin-dynamic-import/blob/v1.1.0/src/index.ts#L31

0.9.9
https://github.com/vite-plugin/vite-plugin-dynamic-import/blob/v0.9.9/src/index.ts#L25

**Comment by shooterRao** [comment]
现在只能回退使用 0.2.0，0.2.1 启动就会报这个错 😂
因为 0.2.1 依赖了 `vite-plugin-dynamic-import ^1.0.0`，依赖实际会安装 `vite-plugin-dynamic-import 1.1.0`，1.1.0 utils 没导出 `normallyImporteeRE` 方法导致报错了

**Comment by caoxiemeihao** [comment]
有两个地方需要改动，暂时发一个 v0.2.2 版本。
v0.2.3 预计下周发布

**Comment by caoxiemeihao** [comment]
Now, `vite-require` [![NPM version](https://img.shields.io/npm/v/vite-require.svg)](https://npmjs.org/package/vite-require) is available.
